dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry install
  - echo -e "machine annofab.com\nlogin FOO\npassword BAR\n" > ~/.netrc && chmod 600 ~/.netrc
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - master
