version: ~> 1.0
dist: focal
language: python
python:
  - "3.7"
  # - "3.8"
  # - "3.9"
  # - "3.10"
install:
  - python -m pip install pip --upgrade 
  - python -m pip --version
  - python -m pip install poetry
  - which pip
  - find / -name pip
  - travis_retry poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - main
env:
  - PIP_DEFAULT_TIMEOUT=100

