version: ~> 1.0
dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"
install:
  - pip install pip --upgrade
  - pip install "poetry<1.2"
  - travis_retry poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - main
env:
  - PIP_DEFAULT_TIMEOUT=100

