version: ~> 1.0
dist: focal
language: python

install:
  - pip install pip --upgrade
  - pip install "poetry<1.8"
  - travis_retry poetry install --only main,linter,test --all-extras

script:
   - pytest tests/test_local*.py


jobs:
  include:
    - python: 3.8
    - python: 3.9
    - python: 3.10
    - python: 3.11
    - python: 3.12
      script:
        # 開発環境と同じPythonバージョンのみlintを実行する
        - make lint


branches:
  only:
  - main

env:
  - PIP_DEFAULT_TIMEOUT=100

cache: pip

