dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install . flake8 mypy pylint pytest
  - echo -e "machine annofab.com\nlogin FOO\npassword BAR\n" > ~/.netrc && chmod 600 ~/.netrc
script:
   - flake8 annofabapi
   - mypy annofabapi --config-file setup.cfg
   - pylint annofabapi --rcfile setup.cfg
   - pytest tests/test_local*.py
branches:
  only:
  - master
