dist: xenial
language: python
python:
  - "3.6"
install:
  - pipenv install --dev
script:
  - make lint
  - echo "OK" # dummy
# FIXME https://github:com/kurusugawa-computer/annofab-api-python-client/issues/25
#  - pytest
