dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install poetry
  - poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - master
