version: ~> 1.0
dist: focal
language: python
python:
  - "3.7"
  # - "3.8"
  # - "3.9"
  # - "3.10"
install:
  # python3.7を有効にするまで記述
  - pip install "keyring==23.5.1" "virtualenv==20.14.1"
  - pip install pip poetry --upgrade
  - travis_retry poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - main
env:
  - PIP_DEFAULT_TIMEOUT=100

