version: ~> 1.0
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - poetry install
env:
  # PyPIへのアクセス過多などで失敗するケースがあるので、タイムアウトを設定する
  - PIP_DEFAULT_TIMEOUT=100
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - master
