version: ~> 1.0
language: python
python:
  - "3.6"
  # 3.7.0だとpylintのエラーが発生するので、3.7.2を指定した
  - "3.7.2"
  - "3.8"
  - "3.9"
install:
  - pip install poetry
  - travis_retry poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - master
env:
  - PIP_DEFAULT_TIMEOUT=100

cache: pip


