version: ~> 1.0
dist: focal
language: python
python:
  - "3.7"
  # - "3.8"
  # - "3.9"
  # - "3.10"
install:
  - find / -name pip -type f 2>/dev/null | xargs -I@ bash -c "@ --version && echo @"
  - python -m pip --version
  - python -m pip install -U pip
  - python -m pip --version
  - find / -name pip -type f 2>/dev/null | xargs -I@ bash -c "@ --version && echo @"
  - wget https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py  
  - which pip
  - python -m pip install poetry
  - travis_retry poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - main
env:
  - PIP_DEFAULT_TIMEOUT=100

