version: ~> 1.0
dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install poetry
  - travis_retry poetry install
script:
   - make lint
   - pytest tests/test_local*.py
branches:
  only:
  - main
env:
  - PIP_DEFAULT_TIMEOUT=100

cache: pip
