"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class AnnotationTypeFieldMinWarnRule(str, Enum):
    """
    最小の幅(min_width)と最小の高さ(min_height)がどのような状態になったときにエラーとするかを指定します。  * `and` - min_width、min_heightの両方が最小値未満の場合にエラーとなります。 * `or` - min_width、min_heightのいずれかが最小値未満の場合にエラーとなります。
    """

    """
    allowed enum values
    """
    AND = "and"
    OR = "or"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AnnotationTypeFieldMinWarnRule from a JSON string"""
        return cls(json.loads(json_str))
