"""
swagger-api-components.yaml に記載されたschemaを出力するためのヘッダ部分

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class CommentStatus(str, Enum):
    """
    `comment_type` の値によってコメントのステータスに格納される値とステータスの意味が変わります。  * `onhold` の場合   * `open`（未対応）、`resolved`（対応完了）を指定可能 * `inspection` の場合   * `open`（未対応）、`resolved`（対応完了）、`closed`（対応不要）を指定可能
    """

    """
    allowed enum values
    """
    OPEN = "open"
    RESOLVED = "resolved"
    CLOSED = "closed"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CommentStatus from a JSON string"""
        return cls(json.loads(json_str))
