"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import Self

from annofabapi.pydantic_models.supplementary_data import SupplementaryData
from annofabapi.pydantic_models.supplementary_data_by_input_data_id_identifier import SupplementaryDataByInputDataIdIdentifier


class GetSupplementaryDataInBulkResponse(BaseModel):
    """
    複数の入力データにわたる補助情報取得時のレスポンス
    """

    success: List[SupplementaryData] = Field(description="取得に成功した補助情報")
    failure: List[SupplementaryDataByInputDataIdIdentifier] = Field(description="取得に失敗した補助情報の所属先")
    __properties: ClassVar[List[str]] = ["success", "failure"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetSupplementaryDataInBulkResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in success (list)
        _items = []
        if self.success:
            for _item_success in self.success:
                if _item_success:
                    _items.append(_item_success.to_dict())
            _dict["success"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in failure (list)
        _items = []
        if self.failure:
            for _item_failure in self.failure:
                if _item_failure:
                    _items.append(_item_failure.to_dict())
            _dict["failure"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetSupplementaryDataInBulkResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "success": [SupplementaryData.from_dict(_item) for _item in obj["success"]] if obj.get("success") is not None else None,
                "failure": [SupplementaryDataByInputDataIdIdentifier.from_dict(_item) for _item in obj["failure"]]
                if obj.get("failure") is not None
                else None,
            }
        )
        return _obj
