"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class InputDataOrder(str, Enum):
    """
    タスクに割り当てる入力データの順序  * `name_asc` - 入力データ名の昇順 * `name_desc` - 入力データ名の降順 * `random` - ランダム
    """

    """
    allowed enum values
    """
    NAME_ASC = "name_asc"
    NAME_DESC = "name_desc"
    RANDOM = "random"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InputDataOrder from a JSON string"""
        return cls(json.loads(json_str))
