"""
swagger-api-components.yaml に記載されたschemaを出力するためのヘッダ部分

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self

from annofabapi.pydantic_models.input_data_type import InputDataType


class InputDataSet(BaseModel):
    """
    入力データセットの情報を表すデータ構造です。
    """

    input_data_set_id: StrictStr = Field(description="入力データセットID。[値の制約についてはこちら。](#section/API-Convention/APIID) ")
    input_data_set_name: StrictStr = Field(description="入力データセットの名前")
    organization_id: StrictStr = Field(description="組織ID。[値の制約についてはこちら。](#section/API-Convention/APIID) ")
    input_data_type: InputDataType
    private_storage_arn: Optional[StrictStr] = Field(
        default=None,
        description="AWS IAMロール。S3プライベートストレージの認可で使います。 [S3プライベートストレージの認可の設定についてはこちら](/docs/faq/#m0b240)をご覧ください。 ",
    )
    updated_datetime: str = Field(description="入力データセットの最終更新日時")
    __properties: ClassVar[List[str]] = [
        "input_data_set_id",
        "input_data_set_name",
        "organization_id",
        "input_data_type",
        "private_storage_arn",
        "updated_datetime",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InputDataSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InputDataSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "input_data_set_id": obj.get("input_data_set_id"),
                "input_data_set_name": obj.get("input_data_set_name"),
                "organization_id": obj.get("organization_id"),
                "input_data_type": obj.get("input_data_type"),
                "private_storage_arn": obj.get("private_storage_arn"),
                "updated_datetime": obj.get("updated_datetime"),
            }
        )
        return _obj
