"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from annofabapi.pydantic_models.marker import Marker


class Markers(BaseModel):
    """
    Markers
    """

    project_id: StrictStr = Field(
        description="プロジェクトID。[値の制約についてはこちら。](#section/API-Convention/APIID) ",
        json_schema_extra={"examples": ["12345678-abcd-1234-abcd-1234abcd5678"]},
    )
    markers: List[Marker] = Field(description="マーカー一覧")
    updated_datetime: str | None = Field(default=None, description="更新日時")
    __properties: ClassVar[List[str]] = ["project_id", "markers", "updated_datetime"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Markers from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in markers (list)
        _items = []
        if self.markers:
            for _item_markers in self.markers:
                _items.append(_item_markers.to_dict() if _item_markers is not None else None)
            _dict["markers"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of Markers from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "project_id": obj.get("project_id"),
                "markers": [Marker.from_dict(_item) for _item in obj["markers"]] if obj.get("markers") is not None else None,
                "updated_datetime": obj.get("updated_datetime"),
            }
        )
        return _obj
