"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Self

from annofabapi.pydantic_models.personal_access_token_permission_all import PersonalAccessTokenPermissionAll


class PersonalAccessToken(BaseModel):
    """
    パーソナルアクセストークン
    """

    id: StrictStr = Field(
        description="パーソナルアクセストークンのID。ユーザごとに一意な文字列。 [値の制約についてはこちら。](#section/API-Convention/APIID) ",
        json_schema_extra={"examples": ["my-personal-access-token"]},
    )
    token: StrictStr = Field(
        description="APIアクセスに用いるトークン文字列。 リクエストヘッダにおいて `Authorization: Bearer {token}` の形で指定します。 "
    )
    account_id: StrictStr = Field(
        description="アカウントID。[値の制約についてはこちら。](#section/API-Convention/APIID) ",
        json_schema_extra={"examples": ["12345678-abcd-1234-abcd-1234abcd5678"]},
    )
    note: StrictStr = Field(description="人間可読なトークンの説明")
    expired_datetime: str = Field(description="トークンの有効期限")
    permissions: List[PersonalAccessTokenPermissionAll] = Field(description="トークンが持つ権限")
    created_datetime: str = Field(description="トークンの作成時刻")
    last_used_datetime: str | None = Field(default=None, description="トークンの最終利用時刻")
    __properties: ClassVar[List[str]] = [
        "id",
        "token",
        "account_id",
        "note",
        "expired_datetime",
        "permissions",
        "created_datetime",
        "last_used_datetime",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PersonalAccessToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in permissions (list)
        _items = []
        if self.permissions:
            for _item_permissions in self.permissions:
                _items.append(_item_permissions.to_dict() if _item_permissions is not None else None)
            _dict["permissions"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of PersonalAccessToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "token": obj.get("token"),
                "account_id": obj.get("account_id"),
                "note": obj.get("note"),
                "expired_datetime": obj.get("expired_datetime"),
                "permissions": [PersonalAccessTokenPermissionAll.from_dict(_item) for _item in obj["permissions"]]
                if obj.get("permissions") is not None
                else None,
                "created_datetime": obj.get("created_datetime"),
                "last_used_datetime": obj.get("last_used_datetime"),
            }
        )
        return _obj
