"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self

from annofabapi.pydantic_models.key_layout import KeyLayout


class ProjectGuestUserProfile(BaseModel):
    """
    ゲストユーザーのプロフィール情報
    """

    user_id: StrictStr = Field(
        description="ゲストユーザーのIDです。 同じ文字列の場合、同じゲストユーザーとして認識されます。 [値の制約についてはこちら。](#section/API-Convention/APIID)"
    )
    user_name: StrictStr = Field(description="ユーザー名")
    lang: StrictStr = Field(description="ゲストユーザーのUIの表示言語です")
    key_layout: KeyLayout
    __properties: ClassVar[List[str]] = ["user_id", "user_name", "lang", "key_layout"]

    @field_validator("lang")
    def lang_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["en-US", "ja-JP", "vi-VN"]):
            raise ValueError("must be one of enum values ('en-US', 'ja-JP', 'vi-VN')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ProjectGuestUserProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of ProjectGuestUserProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {"user_id": obj.get("user_id"), "user_name": obj.get("user_name"), "lang": obj.get("lang"), "key_layout": obj.get("key_layout")}
        )
        return _obj
