"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from pydantic_core import to_jsonable_python
from typing_extensions import Annotated, Self

from annofabapi.pydantic_models.task_phase import TaskPhase


class TaskHistory(BaseModel):
    """
    タスクのあるフェーズで、誰がいつどれくらいの作業時間を費やしたかを表すタスク履歴です。
    """

    project_id: StrictStr = Field(
        description="プロジェクトID。[値の制約についてはこちら。](#section/API-Convention/APIID) ",
        json_schema_extra={"examples": ["12345678-abcd-1234-abcd-1234abcd5678"]},
    )
    task_id: StrictStr = Field(
        description="タスクID。[値の制約についてはこちら。](#section/API-Convention/APIID) ", json_schema_extra={"examples": ["task_001"]}
    )
    task_history_id: StrictStr = Field(
        description="タスク履歴ID。[値の制約についてはこちら。](#section/API-Convention/APIID) ",
        json_schema_extra={"examples": ["12345678-abcd-1234-abcd-1234abcd5678"]},
    )
    started_datetime: str | None = Field(default=None, description="開始日時")
    ended_datetime: str | None = Field(default=None, description="終了日時")
    accumulated_labor_time_milliseconds: StrictStr = Field(
        description="累計実作業時間（ISO 8601 duration）", json_schema_extra={"examples": ["PT34H17M36.789S"]}
    )
    phase: TaskPhase
    phase_stage: Annotated[int, Field(strict=True, ge=1)] = Field(description="タスクのフェーズのステージ番号")
    account_id: StrictStr | None = Field(
        default=None,
        description="アカウントID。[値の制約についてはこちら。](#section/API-Convention/APIID) ",
        json_schema_extra={"examples": ["12345678-abcd-1234-abcd-1234abcd5678"]},
    )
    __properties: ClassVar[List[str]] = [
        "project_id",
        "task_id",
        "task_history_id",
        "started_datetime",
        "ended_datetime",
        "accumulated_labor_time_milliseconds",
        "phase",
        "phase_stage",
        "account_id",
    ]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TaskHistory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict[str, Any] | None) -> Self | None:
        """Create an instance of TaskHistory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "project_id": obj.get("project_id"),
                "task_id": obj.get("task_id"),
                "task_history_id": obj.get("task_history_id"),
                "started_datetime": obj.get("started_datetime"),
                "ended_datetime": obj.get("ended_datetime"),
                "accumulated_labor_time_milliseconds": obj.get("accumulated_labor_time_milliseconds"),
                "phase": obj.get("phase"),
                "phase_stage": obj.get("phase_stage"),
                "account_id": obj.get("account_id"),
            }
        )
        return _obj
