"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class WebhookStatus(str, Enum):
    """
    Webhookの状態
    """

    """
    allowed enum values
    """
    ACTIVE = "active"
    INACTIVE = "inactive"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookStatus from a JSON string"""
        return cls(json.loads(json_str))
